name: build

# on: [push]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Setting up python 3.12
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Validate schema
        run: |
          python -m pip install check-jsonschema
          check-jsonschema --check-metaschema schemas/qwc-db-auth.json

    build:
      needs: test
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      steps:

      - uses: actions/checkout@master

      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ endsWith(github.ref, '-lts') }} = true ]; then
            echo "tag=latest-lts,latest-${GITHUB_REF:11:4}-lts,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          else
            echo "tag=latest,${GITHUB_REF:10}" >>$GITHUB_OUTPUT
          fi

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        if: github.event_name != 'pull_request'
        with:
          name: your-docker-username/your-repo-name
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }}"
